apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: golang-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-webserver
    spec:
      containers:
        - name: golang
          image: newerton/golang-webserver
          ports:
            - containerPort: 8000
